### ISSUE TITLE
PhyML binary exists, but it cannot be executed

### ISSUE THREAD

**Issue by berge2015** [ddarriba/jmodeltest2#38]
Hello,

I am using jModeltest 2.1.10 v20160303 on Linux 2.6.32-642.6.2.el6.x86_64 with PhyML_3.0_linux64 located in the /dist/exe/phyml/ directory.

But when I run the following command 
`java -jar dist/jModelTest.jar -d dist/example-data/aP6.fas -g 4 -f -AIC -BIC -a`
as shown in the manual, I get the error 'PhyML binary exists, but it cannot be executed'

What could be the issue? I mainly tried the fas and phy input files from the examples directory. Thank you for your time.

Edited to add my java version:
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)

**Comment by berge2015** [comment]
The problem was lack of execution permissions. chmod +x fixed it. Thanks to Diego for answering promptly over on google groups. https://groups.google.com/forum/#!topic/jmodeltest/HWvplNv3nAg

**Comment by MdUmar-tech** [comment]
I TRIED with chmod + x BUT SHOWING Bad CPU type in executable
